name: news_app_clean_architecture
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

    # state management
  flutter_bloc: ^8.1.5

  # comparing dart objects
  equatable: ^2.0.5

  # service locator
  get_it: ^7.7.0
  dio: ^5.4.3+1

# date format
intl: ^0.19.0

# database
floor: ^1.5.0

# make a api request
retrofit: ^4.1.0

# hooks
flutter_hooks: ^0.20.5

# cached image
cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  retrofit_generator: ^8.1.0
  floor_generator: ^1.5.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
